In [2]:
import torch
import torch.nn as nn

## **Задача 2**. Cделать нейрон, соответствующий оператору НЕ.

In [3]:
import torch
from torch import nn # модуль с базовыми слоями
import torch.nn.functional as F # модуль с базовыми функциями
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc=nn.Linear(in_features=1,out_features=1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [4]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[0.4849]], requires_grad=True), Parameter containing:
 tensor([0.4113], requires_grad=True))

In [5]:
neuron.fc.weight.data = torch.tensor([[-1.0]])
neuron.fc.bias.data = torch.tensor([1.0])

In [6]:
x = torch.tensor([1.0])
neuron(x)

tensor([0.], grad_fn=<NotImplemented>)

## **Задача 3**. Cделать нейрон, соответствующий оператору И.

In [7]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [8]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.3508, -0.1884]], requires_grad=True), Parameter containing:
 tensor([-0.4855], requires_grad=True))

In [9]:
neuron.fc.weight.data = torch.tensor([[1.0, 1.0]])
neuron.fc.bias.data = torch.tensor([-1.0])

In [10]:
x = torch.tensor([1.0, 1.0])
neuron(x)

tensor([1.], grad_fn=<NotImplemented>)

## **Задача 4**. Cделать нейрон, соответствующий оператору ИЛИ.

In [11]:
neuron.fc.weight.data = torch.tensor([[1.0, 1.0]])
neuron.fc.bias.data = torch.tensor([-0.5])

In [12]:
x = torch.tensor([0.0,1.0])
neuron(x)

tensor([1.], grad_fn=<NotImplemented>)

## **Вопрос 1**. Какие нейронные сети могут иметь только линейную разделяющую поверхность?

Такие, в которых Только один нейрон, либо такие, которые НЕ имеют функцию активации

## **Вопрос 2**. Имеет ли смысл соединять полносвязанные нейроны (нейроны, которые принимают на вход все выходы предыдущего слоя) с линейной функцией активации в многослойную нейронную сеть?

Нет смысла

##**Домашнее задание 1:** реализуйте XOR с помощью 3 нейронов. Запишите ответ в виде выражения, состоящего из объектов neuron() – моделей нейрона с пороговой функцией активации, внутри скобок может быть что угодно. Входы верхнего уровня называются x1 и x2. Пример фрагмента записи: neuron(1*x1 + 5*x2 - 0.1) + neuron(x1) (ответ будет выглядеть чуть сложнее, но других символов вроде && не потребуется).

neuron(neuron(1 *x1-1*x2)+neuron(-1*x1+1*x2))

In [13]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [14]:
neuron1 = Neuron()
neuron2= Neuron()
neuronOR=Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[1., 1.]], requires_grad=True), Parameter containing:
 tensor([-0.5000], requires_grad=True))

In [15]:
neuron1.fc.weight.data = torch.tensor([[1.0, -1.0]])
neuron1.fc.bias.data = torch.tensor([0.0])

neuron2.fc.weight.data = torch.tensor([[-1.0, 1.0]])
neuron2.fc.bias.data = torch.tensor([0.0])

neuronOR.fc.weight.data = torch.tensor([[1.0, 1.0]])
neuronOR.fc.bias.data = torch.tensor([-0.4])

In [17]:
x = torch.tensor([0.0,1.0])# здесь менять
a= torch.Tensor([neuron1(x).data , neuron2(x).data])
neuronOR(a)

tensor([1.], grad_fn=<NotImplemented>)



```
# Выбран кодовый формат
```

##**Домашнее задание 3:** Поэксперементируйте с размером тензоров, которые влезут на видеоркарту в Colab. Найдите максимальный размер тензора для типа данных float32, float64, float16, int32, int64. На сколько они отличаются.

In [18]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.cuda.get_device_properties(0)
def allocate_empty_tensor(dim_size):
  a=torch.zeros(4096,dim_size,dtype=torch.float32,device='cuda')

In [19]:
allocate_empty_tensor(927600)

In [20]:
!nvidia-smi

Sun Dec  4 15:53:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    26W /  70W |  15102MiB / 15109MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

 Максимальный размер для torch.float32 - 4096 на 927600 элементов

In [21]:
torch.cuda.empty_cache()
torch.cuda.memory_reserved()

0

In [22]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.cuda.get_device_properties(0)
def allocate_empty_tensor(dim_size):
  a=torch.zeros(4096,dim_size,dtype=torch.float64,device='cuda')
  print(a.shape)

In [23]:
allocate_empty_tensor(463900)

torch.Size([4096, 463900])


In [24]:
!nvidia-smi

Sun Dec  4 15:53:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    50W /  70W |  15106MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Максимальный размер для float 64 - 4096 на 463900 элементов 

Линейная зависимотсть между float32 и float64. Можно предположить, что float16 вмещает в 4 раза больше элементов, чем float 64, то есть float 16 = 4096 на 1 
 855 600 элементов
 

In [25]:
torch.cuda.empty_cache()
torch.cuda.memory_reserved()

0

In [26]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.cuda.get_device_properties(0)
def allocate_empty_tensor(dim_size):
  a=torch.zeros(4096,dim_size,dtype=torch.int64,device='cuda')
  print(a.shape)

In [27]:
allocate_empty_tensor(463900)

torch.Size([4096, 463900])


In [28]:
!nvidia-smi

Sun Dec  4 15:54:03 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    26W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [29]:
torch.cuda.empty_cache()
torch.cuda.memory_reserved()

0

Такая же ситуация и с INT. Следовательно тип int64=float64, int32=float32 по числу элементов

##**Домашнее задание 4:** Напишите хороший пример неэффективного кода для занятия памяти видеокарты, который вызовет ошибку out of memory

In [39]:
a=torch.rand([40000,1],dtype=torch.float32,device='cuda')
b=torch.ones([1,40000],dtype=torch.float32,device='cuda')
c=a*b

RuntimeError: ignored

In [30]:
torch.cuda.empty_cache()
torch.cuda.memory_reserved()

0

##**Домашнее задание 5:** Используя один линейный слой `nn.Linear` и один входной тензор `x` подберите подберите размерности так, чтобы занимать всю видеопамять.
Попробуйте применить линейный слой к тензору `x`. Что произойдет? Кратко опишите ваши эксперименты. Что вы поняли?

In [31]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0],dtype=torch.float32,device='cuda'))

In [32]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias
neuron.fc.weight.data = torch.rand([30000,30000],dtype=torch.float32,device='cuda')
neuron.fc.bias.data = torch.rand([30000,30000],dtype=torch.float32,device='cuda')

In [33]:
x = torch.rand([30000, 30000],dtype=torch.float32,device='cuda')

In [34]:
!nvidia-smi

Sun Dec  4 15:54:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    26W /  70W |  10910MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [35]:
neuron.to(device)

Neuron(
  (fc): Linear(in_features=2, out_features=1, bias=True)
)

In [36]:
neuron(x)

RuntimeError: ignored

Сделано! Мы получили ошибку out of memory после того как все данные были, но еще не взаимодействовали с нейроном. Взаимодействие с ним также забирает себе GPU, причем внушительную часть (30% плюсом)